image: cprov/stoq:candidate

before_script:
  - easy_install3 pip
  - pip install pytest pytest-cov vcrpy

stages:
  - test

.only-default: &only-default
  only:
    - master
    - merge_requests

test:
  <<: *only-default
  script:
    - pytest -x
