[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_first_party = "stoq,stoqlib,kiwi"
known_localfolder = "tests,<input-main-project-module-here>"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
